name: insta_assets_crop_new
description: A flutter plugin to crop image in insta_assets_picker package. Fork of image_crop package.
version: 0.0.2
homepage: https://github.com/ps6067966/image_crop

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.11"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: fr.legoffmael.imagecrop
        pluginClass: ImageCropPlugin
      ios:
        pluginClass: ImageCropPlugin
